apiVersion: v1
kind: Service
metadata:
  name: firenet-notification-edge
  labels:
    model: firenet
    function: notification
    env: edge
spec:
  type: NodePort
  selector:
    model: firenet
    function: notification
    env: edge
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30909