apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: firenet-server-edge
  labels:
    model: firenet
    function: server
    env: edge
spec:
  replicas: 1
  selector:
    matchLabels:
      model: firenet
      function: server
      env: edge
  template:
    metadata:
      labels:
        model: firenet
        function: server
        env: edge
    spec:
      containers:
      - name: firenet-server-edge
        image: tigonguyen/firedetection:firenet-server-edge
        ports:
            - containerPort: 8000
              protocol: TCP
      nodeName: jetson-nano