apiVersion: v1
kind: Service
metadata:
  name: firenet-server-edge
  labels:
    model: firenet
    function: server
    env: edge
spec:
  type: NodePort
  selector:
    model: firenet
    function: server
    env: edge
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30900