apiVersion: v1
kind: Service
metadata:
  name: firenet-server
  labels:
    model: firenet
    function: server
    env: cloud
spec:
  type: NodePort
  selector:
    model: firenet
    function: server
    env: cloud
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800