apiVersion: v1
kind: Service
metadata:
  name: firenet-notification
  labels:
    model: firenet
    function: notification
    env: cloud
spec:
  type: NodePort
  selector:
    model: firenet
    function: notification
    env: cloud
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808